services:
  sentiment-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/assets
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python -c "import urllib.request, sys; urllib.request.urlopen(''http://localhost:8000/docs''); sys.exit(0)" || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
