version: "3.8"

services:
  sentiment-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
